name: Unit test and code coverage
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: [1.8]
        os: [ubuntu-latest]
        sermant_module: [
            sermant-agentcore-core,
            sermant-agentcore-implement,
            dynamic-config-plugin,
            flowcontrol-common,
            flowcontrol-plugin,
            flowcontrol-service,
            dubbo-loadbalancer-plugin,
            loadbalancer-common,
            loadbalancer-service,
            spring-cloud-loadbalancer-plugin,
            dubbo-router-plugin,
            dubbo-router-service,
            router-config-common,
            spring-router-plugin,
            spring-router-service,
            dubbo-registry-plugin,
            dubbo-registry-service,
            spring-cloud-registry-plugin,
            spring-cloud-registry-service
        ]
    permissions:
      checks: write
      contents: write
      pull-requests: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: download sc
        run: |
          curl -o apache-servicecomb-service-center-2.1.0-linux-amd64.tar.gz -L https://github.com/apache/servicecomb-service-center/releases/download/v2.1.0/apache-servicecomb-service-center-2.1.0-linux-amd64.tar.gz
          tar -zxf apache-servicecomb-service-center-2.1.0-linux-amd64.tar.gz
          sh apache-servicecomb-service-center-2.1.0-linux-amd64/start-service-center.sh
      - name: download zookeeper
        run: |
          curl -o apache-zookeeper-3.8.0-bin.tar.gz -L https://dlcdn.apache.org/zookeeper/zookeeper-3.8.0/apache-zookeeper-3.8.0-bin.tar.gz
          tar -zxf apache-zookeeper-3.8.0-bin.tar.gz
          bash apache-zookeeper-3.8.0-bin/bin/zkServer.sh start apache-zookeeper-3.8.0-bin/conf/zoo_sample.cfg
      - name: Build with Maven
        run: |
          mvn install -DskipTests
          mvn test -pl com.huaweicloud.sermant:${{ matrix.sermant_module }}
      - name: Generate code coverage report
        uses: codecov/codecov-action@v3
        with:
          files: '**/target/jacoco-report/jacoco.xml'
          flags: unittests
          fail_ci_if_error: true # optional (default = false)