name: Workflow for Jacoco
on: [push, pull_request]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: [1.8]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn test
      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.6
        with:
          coverage_results_path: ${{ github.workspace }}/sermant-agentcore/sermant-agentcore-core/target/jacoco-report/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false
#      - name: Publish Code Coverage in PR
#        id: jacoco
#        uses: madrapps/jacoco-report@v1.2
#        with:
#          paths: ${{ github.workspace }}/sermant-agentcore/sermant-agentcore-core/target/jacoco-report/jacoco.xml
#          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 11
#          min-coverage-changed-files: 11
#          debug-mode: true
      - name: config codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
      - name: Publish test coverage results
        uses: PavanMudigonda/jacoco-reporter@v4.6
        with:
          coverage_results_path: 'sermant-agentcore/sermant-agentcore-core/target/jacoco-report/jacoco.xml'
          coverage_report_title: 'Test coverage results'
          coverage_report_name: 'Test coverage results'
          github_token: ${{ secrets.GITHUB_TOKEN }}